# Generated by Django 3.1.5 on 2021-02-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Life',
            fields=[
                ('ID', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('lastEditTime', models.DateTimeField(auto_now_add=True)),
                ('lifeName', models.CharField(max_length=20, verbose_name='lifeName')),
                ('lifeText', models.TextField(verbose_name='lifeContext')),
                ('picture', models.ImageField(null=True, upload_to='img/', verbose_name='picture')),
            ],
        ),
    ]
