# Generated by Django 3.1.5 on 2021-04-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='life',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file/'),
        ),
        migrations.AlterField(
            model_name='study',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file/'),
        ),
    ]
