# Generated by Django 3.1.5 on 2021-02-24 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xunzhou', '0002_user'),
        ('blogs', '0003_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='xunzhou.user'),
        ),
    ]
