# Generated by Django 3.1.5 on 2021-03-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='note',
            field=models.FileField(null=True, upload_to='notes/%Y/%m/%d/'),
        ),
    ]
