# Generated by Django 3.1.5 on 2021-03-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_study_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='mark',
            field=models.CharField(max_length=50),
        ),
    ]
