# Generated by Django 3.1.5 on 2021-03-25 21:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20210326_0444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='life',
            old_name='lifeName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='life',
            name='lifeText',
        ),
        migrations.AddField(
            model_name='life',
            name='text',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
