# Generated by Django 3.1.5 on 2021-04-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('UserName', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='UserName')),
                ('UserPasswd', models.CharField(max_length=20, verbose_name='UserPasswd')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='picture')),
            ],
        ),
    ]
