# Generated by Django 3.1.5 on 2021-02-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xunzhou', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('UserName', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='UserName')),
                ('UserPasswd', models.CharField(max_length=20, verbose_name='UserPasswd')),
                ('photo', models.ImageField(null=True, upload_to='img/', verbose_name='picture')),
            ],
        ),
    ]
