# Generated by Django 3.1.5 on 2021-03-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xunzhou', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='picture'),
        ),
    ]
